### ISSUE TITLE
Limit?

### ISSUE THREAD

**Issue by avenantsoftware** [blha303/mp3list#1]
Is there some sort of limit on how many mp3's can be listed?

I have a folder of 100 audio books, with only the audio books it works just fine

however when I add a folder with about 600 mp3's it is no longer working...

Then apache throws a 500 server error.

If I then again remove the folder with the 600 mp3's it works again...

or could it be something with the naming of the mp3's?

the 600 mp3's are named:

"0001. Artist Name - Song Title.mp3"
"0002. Artist Name - Song 2 Title.mp3"

etc..

**Comment by blha303** [comment]
Can you tail -f /var/log/apache2/error.log and try the page again to see what error is being produced?

**Comment by blha303** [comment]
Oh, I forgot I ported this to Python. Check the server log wherever you're running the flask server from. If it shows the 500 error but no message associated, you'll need to turn on debug mode.

**Comment by blha303** [comment]
No reply, closing thread
